import { describe, expect, it } from 'vitest';
import { nextDefaultName, nextSeq, uniqueName, validateId } from '../src/shared/workspace';
import { maskDsn, maskSecret, stripDsnFromTblsConfig } from '../src/tbls/runner';

describe('ids', () => {
  it('validates the slug format and uniqueness', () => {
    expect(validateId('main-db', [])).toBeUndefined();
    expect(validateId('Main', [])).toBeDefined();
    expect(validateId('-x', [])).toBeDefined();
    expect(validateId('a', ['a'])).toContain('已存在');
  });

  it('numbers from the directories when there is no counter', () => {
    expect(nextSeq('design', [])).toBe(1);
    expect(nextSeq('design', ['design1', 'design2'])).toBe(3);
    expect(nextSeq('design', ['design2', 'design10'])).toBe(11);
  });

  it('never reuses a number: takes the larger of counter and directories', () => {
    expect(nextSeq('design', ['design1'], 3)).toBe(4);
    expect(nextSeq('design', ['design7'], 3)).toBe(8);
  });

  it('ignores ids that do not follow the <prefix><N> form', () => {
    expect(nextSeq('design', ['order-system', 'design-1', 'designx', 'db9'])).toBe(1);
    expect(nextSeq('db', ['db1', 'dbx2', 'db02'])).toBe(3);
  });
});

describe('default names', () => {
  it('counts from one past the highest default name', () => {
    expect(nextDefaultName('画布', [])).toBe('画布 1');
    expect(nextDefaultName('画布', ['画布 1', '画布 3'])).toBe('画布 4');
    expect(nextDefaultName('画布', ['画布 1', '画布 2'].filter((n) => n !== '画布 2'))).toBe('画布 2');
  });

  it('ignores names the user chose', () => {
    expect(nextDefaultName('设计库', ['核心模型', '设计库A', '设计库 x', '我的设计库 5'])).toBe('设计库 1');
  });

  it('adds a suffix to taken names', () => {
    expect(uniqueName('PostgreSQL · orders', [])).toBe('PostgreSQL · orders');
    expect(uniqueName('PostgreSQL · orders', ['PostgreSQL · orders'])).toBe('PostgreSQL · orders (2)');
    expect(uniqueName('PostgreSQL · orders', ['PostgreSQL · orders', 'PostgreSQL · orders (2)'])).toBe('PostgreSQL · orders (3)');
  });
});

// Placeholder credentials only; never paste a real DSN into tests.
const DSN = 'postgres://reader:example-secret@db.example.test:5432/app?sslmode=disable';

describe('dsn handling', () => {
  it('strips the dsn from a tbls config and keeps comments', () => {
    const input = `# generated by tbls\n\ndsn: ${DSN}\n# where docs go\ndocPath: doc/schema\n`;
    const { text, dsn } = stripDsnFromTblsConfig(input);
    expect(dsn).toBe(DSN);
    expect(text).not.toContain('example-secret');
    expect(text).toContain('# generated by tbls');
    expect(text).toContain('# where docs go\ndocPath: doc/schema');
  });

  it('leaves configs without a dsn untouched', () => {
    const input = 'docPath: doc\n';
    expect(stripDsnFromTblsConfig(input)).toEqual({ text: input });
  });

  it('masks passwords', () => {
    expect(maskDsn(DSN)).toBe('postgres://reader:****@db.example.test:5432/app?sslmode=disable');
    const message = `failed to connect ${DSN}; password example-secret rejected`;
    const masked = maskSecret(message, DSN);
    expect(masked).not.toContain('example-secret');
  });
});
